### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 123Sun556** [bobolike123/NetworkTrafficAnalysis#2]
您好，请问有处理后的数据集吗 文件中没有找到

**Comment by bobolike123** [comment]
留下邮箱，我发给你

**Comment by bobolike123** [comment]
Readme已更新链接，请注意查看

**Comment by 123Sun556** [comment]
非常感谢!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月8日(周五) 晚上10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bobolike123/NetworkTrafficAnalysis] 数据集 (Issue #2)




 
Readme已更新链接，请注意查看

**Comment by parkourlrc** [comment]
请问处理过的数据集还有不

**Comment by parkourlrc** [comment]
> 您好，请问有处理后的数据集吗 文件中没有找到
您好，请问您那里有处理过的数据集吗，可以发我一份吗，我的邮箱是2976174591@qq.com
万分感谢

**Comment by 123Sun556** [comment]
非常抱歉 我没有在电脑里找到🥹



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: parkourlrc ***@***.***&gt;
发送时间: 2024年1月25日 23:48
收件人: bobolike123/NetworkTrafficAnalysis ***@***.***&gt;
抄送: 123Sun556 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bobolike123/NetworkTrafficAnalysis] 数据集 (Issue #2)





  
您好，请问有处理后的数据集吗 文件中没有找到
 ***@***.***
 万分感谢
